name: CMake

on: [push]

jobs:
  Linux:
    name: Build on ubuntu-latest
    
    runs-on: ubuntu-latest
    
    env:
      BUILD_TYPE: Release
      CC: ${{ matrix.cc }}
      CXX: ${{ matrix.cxx }}
  
    strategy:
      fail-fast: false
      matrix:
        BUILD_TESTING: ['OFF']
        NO_FONT_INTERFACE_DEFAULT: ['OFF']
        DISABLE_RTTI_AND_EXCEPTIONS: ['OFF']
        NO_THIRDPARTY_CONTAINERS: ['OFF']
        cc: ['clang']
        cxx: ['clang++']
        include:
          - BUILD_TESTING: 'ON'
          - NO_FONT_INTERFACE_DEFAULT: 'ON'
          - DISABLE_RTTI_AND_EXCEPTIONS: 'ON'
            NO_THIRDPARTY_CONTAINERS: 'ON'
            cc: gcc
            cxx: g++

    steps:
    - uses: actions/checkout@v2
      
    - name: Install Dependencies
      run: sudo apt-get install cmake ninja-build libsdl2-dev libsdl2-image-dev libfreetype6-dev libglew-dev liblua5.2-dev libsfml-dev
      
    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/Build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/Build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_LUA_BINDINGS=ON -DBUILD_SAMPLES=ON -DBUILD_TESTING=${{ matrix.BUILD_TESTING }} -DWARNINGS_AS_ERRORS=ON

    - name: Build
      working-directory: ${{runner.workspace}}/Build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE

    - name: Test
      if: ${{ matrix.BUILD_TESTING == 'ON' }}
      working-directory: ${{runner.workspace}}/Build
      shell: bash
      run: ctest -C $BUILD_TYPE


  MacOS:
    name: Build on macos-latest
    
    runs-on: macos-latest
    
    env:
      BUILD_TYPE: Release

    steps:
    - uses: actions/checkout@v2
      
    - name: Install Dependencies
      run: brew install lua
      
    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/Build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/Build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_LUA_BINDINGS=ON -DBUILD_SAMPLES=ON -DWARNINGS_AS_ERRORS=ON

    - name: Build
      working-directory: ${{runner.workspace}}/Build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE
